---
title: "MRC IEU software metrics"
author: TP
date-modified: last-modified
format:
  html:
    embed-resources: true
    code-fold: true
    code-summary: "Show the code"
---

## R packages

* Raw download count of MRC IEU authored and co-authored R packages on CRAN

```{r setup, warning=FALSE}
library(packageRank)
library(ggplot2)
library(PrettyCols)
library(scales)
```

```{r}
dat <- 
  cranDownloads(
    packages = c(
      "OneSampleMR",
      "ieugwasr",
      "epigraphdb",
      "tmsens",
      "mrbayes",
      "bpbounds",
      "Statamarkdown",
      "midoc",
      "SEQTaRget"
    ),
    from = "2018",
    to = Sys.Date() - 1,
    fix.cranlogs = TRUE
  )
dat$cranlogs.data |>
  ggplot() + 
  aes(x = date, y = cumulative, color = package) + 
  geom_line(linewidth = 0.75) + 
  scale_y_continuous(labels = label_comma()) +
  scale_color_pretty_d(palette = "Autumn") + 
  ylab("Cumulative downloads") +
  xlab("Date") +
  labs(color = 'Package') 
```

* Comparison with non-IEU MendelianRandomization package

```{r}
dat2 <- 
  cranDownloads(
    packages = c(
      "MendelianRandomization",
      "ieugwasr"
    ),
    from = "2016-08-31",
    to = Sys.Date() - 1,
    fix.cranlogs = TRUE
  )
dat2$cranlogs.data |>
  ggplot() + 
  aes(x = date, y = cumulative, color = package) + 
  geom_line(linewidth = 0.75) + 
  scale_y_continuous(labels = label_comma()) +
  scale_color_pretty_d(palette = "Autumn") + 
  ylab("Cumulative downloads") +
  xlab("Date") +
  labs(color = 'Package')
```

## Python packages

* ieugwaspy

```{=html}
<iframe src="https://pypistats.org/packages/ieugwaspy" width="900" height="400"></iframe>
```

* pygwasvcf

```{=html}
<iframe src="https://pypistats.org/packages/pygwasvcf" width="900" height="400"></iframe>
```

* pySEQTarget

```{=html}
<iframe src="https://pypistats.org/packages/pySEQTarget" width="900" height="400"></iframe>
```

## Links to article citations

* MR-Base paper: <https://elifesciences.org/articles/34408>
* MR-Steiger paper: <https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007081>
